name: Implementing the GHA action

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checking out repo
              uses: actions/checkout@v4

            - name: Listing the files
              run: ls -a


